### PR TITLE
Removed files 

### PR DESCRIPTION
**Pull request by sswatisharmaa**
Removing files that are not needed.

### CODE REVIEW

**Comment by anurag091** [comment]
@sswatisharmaa `src/app/models/codeMos.ts` did you keep that blank intentionally?

**Comment by sswatisharmaa** [comment]
> @sswatisharmaa `src/app/models/codeMos.ts` did you keep that blank intentionally?

Yes. Wanted to commit different folders for components, services and models. But that can be done as we proceed with coding.

**Review by anurag091 — DISMISSED** [review]
LGTM

**Comment by tiwariutkarsh422** [comment]
> > @sswatisharmaa `src/app/models/codeMos.ts` did you keep that blank intentionally?
> 
> Yes. Wanted to commit different folders for components, services and models. But that can be done as we proceed with coding.

> I think we can create the components in app folder by their respective names directly without creating a separate components folder.

**Comment by anurag091** [comment]
> > > @sswatisharmaa `src/app/models/codeMos.ts` did you keep that blank intentionally?
> > 
> > 
> > Yes. Wanted to commit different folders for components, services and models. But that can be done as we proceed with coding.
> 
> > I think we can create the components in app folder by their respective names directly without creating a separate components folder.

That would not be a very good idea.
structure should be like 
app
     - {all app level files}
     - CommonComponentFolder
     - specificModule Folder(Say Login) 
          - Login.js
          - Login.css
          -Login_test.js

Something like that

**Comment by tiwariutkarsh422** [comment]
> > > > @sswatisharmaa `src/app/models/codeMos.ts` did you keep that blank intentionally?
> > > 
> > > 
> > > Yes. Wanted to commit different folders for components, services and models. But that can be done as we proceed with coding.
> > 
> > 
> > > I think we can create the components in app folder by their respective names directly without creating a separate components folder.
> 
> That would not be a very good idea.
> structure should be like
> app
> - {all app level files}
> - CommonComponentFolder
> - specificModule Folder(Say Login)
> - Login.js
> - Login.css
> -Login_test.js
> 
> Something like that

> so there can be two different logins for admin and user. can we keep that in different folders like
- admin
  - admin_login
  - .....dashboard admin
- user
  - user_login
  - .......dashboard user

**Comment by anurag091** [comment]
> > > > > @sswatisharmaa `src/app/models/codeMos.ts` did you keep that blank intentionally?
> > > > 
> > > > 
> > > > Yes. Wanted to commit different folders for components, services and models. But that can be done as we proceed with coding.
> > > 
> > > 
> > > > I think we can create the components in app folder by their respective names directly without creating a separate components folder.
> > 
> > 
> > That would not be a very good idea.
> > structure should be like
> > app
> > 
> > * {all app level files}
> > * CommonComponentFolder
> > * specificModule Folder(Say Login)
> > * Login.js
> > * Login.css
> >   -Login_test.js
> > 
> > Something like that
> 
> > so there can be two different logins for admin and user. can we keep that in different folders like
> 
> * admin
>   
>   * admin_login
>   * .....dashboard admin
> * user
>   
>   * user_login
>   * .......dashboard user

I believe, there is no admin as for now. We will get the user data through Oauth.

**Review by anurag091 — CHANGES_REQUESTED** [review]
@sswatisharmaa  can you please accommodate the change in this PR itself.

{all app level files}
- CommonComponentFolder
- specificModule Folder(Say Login)
- Login.js
- Login.css
-Login_test.js

**Comment by sswatisharmaa** [comment]
> @sswatisharmaa can you please accommodate the change in this PR itself.
> 
> {all app level files}
> 
> * CommonComponentFolder
> * specificModule Folder(Say Login)
> * Login.js
> * Login.css
>   -Login_test.js





> @sswatisharmaa can you please accommodate the change in this PR itself.
> 
> {all app level files}
> 
> * CommonComponentFolder
> * specificModule Folder(Say Login)
> * Login.js
> * Login.css
>   -Login_test.js


@anurag091, sure. will add the below structure:
1. App folder with subfolders: - a) app level files b) CommonComponents folder c) Login (will contain login.ts, login.css, login_test.ts, login.html)

**Comment by tiwariutkarsh422** [comment]
> > @sswatisharmaa can you please accommodate the change in this PR itself.
> > {all app level files}
> > 
> > * CommonComponentFolder
> > * specificModule Folder(Say Login)
> > * Login.js
> > * Login.css
> >   -Login_test.js
> 
> > @sswatisharmaa can you please accommodate the change in this PR itself.
> > {all app level files}
> > 
> > * CommonComponentFolder
> > * specificModule Folder(Say Login)
> > * Login.js
> > * Login.css
> >   -Login_test.js
> 
> @anurag091, sure. will add the below structure:
> 
> 1. App folder with subfolders: - a) app level files b) CommonComponents folder c) Login (will contain login.ts, login.css, login_test.ts, login.html)

> yes that should be fine. also @anurag091 should a home folder be added for the homepage??

**Comment by anurag091** [comment]
> > > @sswatisharmaa can you please accommodate the change in this PR itself.
> > > {all app level files}
> > > 
> > > * CommonComponentFolder
> > > * specificModule Folder(Say Login)
> > > * Login.js
> > > * Login.css
> > >   -Login_test.js
> > 
> > 
> > > @sswatisharmaa can you please accommodate the change in this PR itself.
> > > {all app level files}
> > > 
> > > * CommonComponentFolder
> > > * specificModule Folder(Say Login)
> > > * Login.js
> > > * Login.css
> > >   -Login_test.js
> > 
> > 
> > @anurag091, sure. will add the below structure:
> > 
> > 1. App folder with subfolders: - a) app level files b) CommonComponents folder c) Login (will contain login.ts, login.css, login_test.ts, login.html)
> 
> > yes that should be fine. also @anurag091 should a home folder be added for the homepage??

There is nothing like homepage(technically). There would be timeline container(groups of clubbed component), left and right layouts. We Will add that on run time.

**Comment by tiwariutkarsh422** [comment]
> > > > @sswatisharmaa can you please accommodate the change in this PR itself.
> > > > {all app level files}
> > > > 
> > > > * CommonComponentFolder
> > > > * specificModule Folder(Say Login)
> > > > * Login.js
> > > > * Login.css
> > > >   -Login_test.js
> > > 
> > > 
> > > > @sswatisharmaa can you please accommodate the change in this PR itself.
> > > > {all app level files}
> > > > 
> > > > * CommonComponentFolder
> > > > * specificModule Folder(Say Login)
> > > > * Login.js
> > > > * Login.css
> > > >   -Login_test.js
> > > 
> > > 
> > > @anurag091, sure. will add the below structure:
> > > 
> > > 1. App folder with subfolders: - a) app level files b) CommonComponents folder c) Login (will contain login.ts, login.css, login_test.ts, login.html)
> > 
> > 
> > > yes that should be fine. also @anurag091 should a home folder be added for the homepage??
> 
> There is nothing like homepage(technically). There would be timeline container(groups of clubbed component), left and right layouts. We Will add that on run time.

> got it

**Review by anurag091 — APPROVED** [review]
lgtm

**Pull request merged**
